version: '3'
services:
  dev:
    build: .
    command: bash -c "yarn && yarn dev"
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    working_dir: /usr/app
    ports:
      - '8080:8080'
  web:
    build: .
    command: yarn start
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    working_dir: /usr/app
    ports:
      - '3030:3030'
  nginx:
    build: ./.moi/nginx-docker
    ports:
      - '80:80'
